---
title: "240P_project"
author: "Jiaxin Li"
date: "2023-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
n <- 5; G <- 3;mu <- matrix(c(0, 0, 0, 1, 2, 3, 4,5,6), nrow = 3, ncol = 3)

Y <- c()
Sigma=diag(c(1,2,3))

mvrnorm(5, c(0,0,0), Sigma)

for (g in 1:G){
  Y <- rbind(Y, mvrnorm(n, mu[g,], Sigma))
  }
Y
```




```{r}
library(MASS)
n <- 500
G <- 3 
mu <- matrix(c(0, 0, 0, 1, 2, 3, -3,-2,-1), nrow = 3, ncol = 3)

generate_data <- function(n, G, mu , Sigma=diag(c(1, 2, 3)))
{
  Y <- c()
  for (g in 1:G){
    Y <- rbind(Y, mvrnorm(n, mu[,g], Sigma))
    }
  Y 
}
Y <- generate_data(n, G, mu)
```

```{r}
groups <- rep(1:G, each=n)
par(mfrow=c(ceiling(G/3), 2 + (G>=3))) 
for (g in 1:G){
  boxplot(Y[which(groups==g), ], ylim=c(-4, 4), main = paste("Group", g))
}
```



```{r}
test <- function(n, G, Y){
  groups <- rep(c(paste("Group", 1:G)), each=n)
  obj <- manova(Y ~ groups)
  tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy") 
  reject <- rep(0, 4)
  for (t in 1:length(tests)){
    reject[t] <- summary(obj, test = tests[t])$stats[1,6]<0.05
    }
  reject 
}
results <- test(n, G, Y)
names(results) <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")
results
```

```{r}
set.seed(2023)

simulate <- function(B, n, G, mu, Sigma = diag(c(1,2,3))){
  results <- rep(0, 4)
  for (b in 1:B){
    Y <- generate_data(n, G, mu, Sigma = Sigma)
    results <- results + test(n, G, Y)
    }
  results/B 
}
simulate(B = 500, n = 100, G = 3, mu=matrix(rep(0,9), nrow = 3, ncol = 3) , Sigma=diag(c(0.1, 0.1, 0.1)) )

```

```{r}
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")
alpha <- simulate(B = 500, n = 100, G = 3, mu=matrix(rep(0,9), nrow = 3, ncol = 3) , Sigma=diag(c(0.1, 0.1, 0.1)) )
names(alpha) <- tests
barplot(alpha, col=c(2:5))
abline(h=0.05)
```

## influence of sample size

```{r}
# Define n values
n_values <- seq(10, 100, 10)

# Initialize matrix to store results
results <- matrix(nrow = length(n_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(n_values)) {
    alpha <- simulate(B = 200, n = n_values[i], G = 3, mu = matrix(rep(0,9), nrow = 3, ncol = 3), Sigma = diag(c(0.1, 0.1, 0.1)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- n_values
colnames(results) <- tests

results

```

```{r}
xvalues <- seq(from = 10, to = 100, by = 10)  # Custom x-axis values
matplot(xvalues, results, type = "l", lty = 1, xlab = "Sample Size", ylab = "Type 1 Error RateZ")
# Add a custom x-axis
axis(side = 1, at = xvalues)
legend("topleft", legend = c("Pillai", "Wilks", "Hotelling-Lawley", "Roy"), col=1:5, lty = 1)


```
## Influence of different covariance matrix.

```{r}
Sigma1=diag(c(1,1,1))
Sigma2=matrix(rep(0.5,9),3,3)+diag(0.5,3)
Sigma3=matrix(rep(-0.2,9),3,3)+diag(1.2,3)
Sigma4=diag(c(1,2,3))
Sigma_list=list(Sigma1,Sigma2, Sigma3, Sigma4)
Sigma_list
```

```{r}

# Initialize matrix to store results
results <- matrix(nrow = 4, ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:4) {
    alpha <- simulate(B = 200, n = 50, G = 3, mu = matrix(rep(0,9), nrow = 3, ncol = 3), Sigma = Sigma_list[[i]])
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- c("I and same", "positive", "negative", "I and differnt")
colnames(results) <- tests

results
```

```{r}
matplot(results, type = "l", lty = 1, xlab = "Cov matrix type", ylab = "Type 1 Error Rate")
legend("topleft", legend = c("Pillai", "Wilks", "Hotelling-Lawley", "Roy"), col=1:5, lty = 1)

```

## Asses by power

```{r}
# Define n values
n_values <- seq(10, 100, 10)

# Initialize matrix to store results
results <- matrix(nrow = length(n_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(n_values)) {
alpha <- simulate(B = 200, n = n_values[i], G = 3, 
                  mu = matrix(rep(c(0,0,1),3), 3,3, byrow = TRUE),
                  Sigma = diag(c(0.1, 0.1, 0.1)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- n_values
colnames(results) <- tests

results
```

change variance to diag(1,1,1)
```{r}
# Define n values
n_values <- seq(10, 100, 10)

# Initialize matrix to store results
results <- matrix(nrow = length(n_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(n_values)) {
alpha <- simulate(B = 200, n = n_values[i], G = 3, 
                  mu = matrix(rep(c(0,0,1),3), 3,3, byrow = TRUE),
                  Sigma = diag(c(1, 1, 1)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- n_values
colnames(results) <- tests

results
```




```{r}
# Define n values
n_values <- seq(10, 100, 10)

# Initialize matrix to store results
results <- matrix(nrow = length(n_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(n_values)) {
alpha <- simulate(B = 200, n = n_values[i], G = 3, 
                  mu = matrix(rep(c(0,0,1),3), 3,3, byrow = TRUE),
                  Sigma = diag(c(5, 5, 5)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- n_values
colnames(results) <- tests

results
```

```{r}
xvalues <- seq(from = 10, to = 100, by = 10)  # Custom x-axis values
matplot(xvalues, results, type = "l", lty = 1, xlab = "Sample Size", ylab = "Power")
# Add a custom x-axis
axis(side = 1, at = xvalues)
legend("topleft", legend = c("Pillai", "Wilks", "Hotelling-Lawley", "Roy"), col=1:5, lty = 1)
```

```{r}
# Define n values
mu_values <- seq(0.1, 3, 0.2)

# Initialize matrix to store results
results <- matrix(nrow = length(mu_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(mu_values)) {
alpha <- simulate(B = 200, n = 40, G = 3, 
                  mu = matrix(rep(c(0,0,mu_values[i]),3), 3,3, byrow = TRUE),
                  Sigma = diag(c(7, 7, 7)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- mu_values
colnames(results) <- tests

results
```

```{r}
xvalues <- seq(0.1, 3, 0.2)
matplot(xvalues, results, type = "l", lty = 1, xlab = "mean difference", ylab = "Power")
# Add a custom x-axis
#axis(side = 1, at = xvalues)
legend("topleft", legend = c("Pillai", "Wilks", "Hotelling-Lawley", "Roy"), col=1:5, lty = 1)
```

```{r}
# Define n values
sigma_values <- seq(0.1, 8.1, 1)

# Initialize matrix to store results
results <- matrix(nrow = length(sigma_values), ncol = 4)

# Define test names
tests <- c("Pillai", "Wilks", "Hotelling-Lawley", "Roy")

# Run simulations
for (i in 1:length(sigma_values)) {
  alpha <- simulate(B = 200, n = 40, G = 3,
                    mu = matrix(rep(c(0,0,mu_values[i]),3), 3,3, byrow = TRUE),
                    Sigma = diag(rep(sigma_values[i],3)))
    names(alpha) <- tests
    results[i, ] <- alpha
}

# Set row and column names of results matrix
rownames(results) <- sigma_values
colnames(results) <- tests

results
```


```{r}
xvalues <- sigma_values
matplot(xvalues, results, type = "l", lty = 1, xlab = "variance", ylab = "Power")
# Add a custom x-axis
#axis(side = 1, at = xvalues)
legend("topleft", legend = c("Pillai", "Wilks", "Hotelling-Lawley", "Roy"), col=1:5, lty = 1)
```



